#!/bin/sh /etc/rc.common
# Copyright (C) 2024 SagerNet

START=95
STOP=10

USE_PROCD=1
PROG=/usr/bin/sing-box
CONF_DIR=/etc/sing-box
CONF_FILE=$CONF_DIR/config.json

start_service() {
    [ -f "$CONF_FILE" ] || return 1

    procd_open_instance
    procd_set_param command /usr/bin/env ENABLE_DEPRECATED_LEGACY_DNS_SERVERS=true ENABLE_DEPRECATED_MISSING_DOMAIN_RESOLVER=true "$PROG" run -c "$CONF_FILE"
    procd_set_param user root
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance

    # Фикс маршрутизации OpenWrt для tun интерфейса
    iptables -t nat -I POSTROUTING -o tun-shuka -j MASQUERADE
    iptables -I FORWARD -o tun-shuka -j ACCEPT
    iptables -I FORWARD -i tun-shuka -j ACCEPT
}

stop_service() {
    service_stop "$PROG"

    # Очистка правил маршрутизации
    iptables -t nat -D POSTROUTING -o tun-shuka -j MASQUERADE 2>/dev/null
    iptables -D FORWARD -o tun-shuka -j ACCEPT 2>/dev/null
    iptables -D FORWARD -i tun-shuka -j ACCEPT 2>/dev/null
}

reload_service() {
    stop
    start
}
