#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1
PROG=/usr/bin/sing-box
CONF_FILE=/etc/sing-box/config.json

start_service() {
    [ -f "$CONF_FILE" ] || return 1
    procd_open_instance
    # Вариант с явным sh -c для 100% проброса переменных
    procd_set_param command /bin/sh -c "ENABLE_DEPRECATED_LEGACY_DNS_SERVERS=true ENABLE_DEPRECATED_MISSING_DOMAIN_RESOLVER=true $PROG run -c $CONF_FILE"
    procd_set_param user root
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance

    # Настройка маршрутизации LAN -> VPN в обход mwan3/vpn-policy-routing
    ip rule add iif br-lan lookup 2022 pref 5000 2>/dev/null
    iptables -I FORWARD -o tun-shuka -j ACCEPT 2>/dev/null
    iptables -I FORWARD -i tun-shuka -j ACCEPT 2>/dev/null
}

stop_service() {
    service_stop "$PROG"

    # Очистка маршрутизации
    ip rule del iif br-lan lookup 2022 pref 5000 2>/dev/null
    iptables -D FORWARD -o tun-shuka -j ACCEPT 2>/dev/null
    iptables -D FORWARD -i tun-shuka -j ACCEPT 2>/dev/null
}

reload_service() {
    stop
    start
}